map:
  MC.PA: "LVMH Moët Hennessy Louis Vuitton"
  OR.PA: "L'Oréal"
  RMS.PA: "Hermès International"
  KER.PA: "Kering"
  SAN.PA: "Sanofi"
  AI.PA: "Air Liquide"
  IPN.PA: "Ipsen"
  BIM.PA: "bioMérieux"
  TTE.PA: "TotalEnergies"
  ENGI.PA: "Engie"
  EDF.PA: "EDF"
  VIE.PA: "Veolia"
  AIR.PA: "Airbus"
  SGO.PA: "Saint-Gobain"
  ALO.PA: "Alstom"
  ERF.PA: "Eiffage"
  VIN.PA: "Vinci"
  BNP.PA: "BNP Paribas"
  ACA.PA: "Crédit Agricole"
  GLE.PA: "Société Générale"
  AMUN.PA: "Amundi"
  CS.PA: "AXA"
  CAP.PA: "Capgemini"
  STM.PA: "STMicroelectronics"
  ILD.PA: "Iliad (Free)"
  ORA.PA: "Orange"
  PUB.PA: "Publicis Groupe"
